import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#003640",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#4edea3",
        "outline-variant": "#4d4354",
        "on-tertiary-container": "#00311f",
        "inverse-surface": "#e5e2e1",
        "on-background": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "surface": "#131313",
        "on-surface-variant": "#cfc2d6",
        "on-primary-container": "#400071",
        "on-secondary-container": "#00424e",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-container": "#00a572",
        "on-tertiary-fixed": "#002113",
        "on-surface": "#e5e2e1",
        "secondary-container": "#03b5d3",
        "on-tertiary": "#003824",
        "on-secondary-fixed": "#001f26",
        "tertiary": "#4edea3",
        "primary-fixed-dim": "#ddb7ff",
        "primary-container": "#b76dff",
        "error-container": "#93000a",
        "surface-container": "#201f1f",
        "on-tertiary-fixed-variant": "#005236",
        "secondary": "#4cd7f6",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-high": "#2a2a2a",
        "on-error": "#690005",
        "surface-container-highest": "#353534",
        "outline": "#988d9f",
        "background": "#131313",
        "secondary-fixed": "#acedff",
        "on-primary-fixed-variant": "#6900b3",
        "secondary-fixed-dim": "#4cd7f6",
        "primary": "#ddb7ff",
        "surface-bright": "#393939",
        "on-primary": "#490080",
        "inverse-on-surface": "#313030",
        "surface-dim": "#131313",
        "surface-tint": "#ddb7ff",
        "on-secondary-fixed-variant": "#004e5c",
        "surface-variant": "#353534",
        "inverse-primary": "#842bd2",
        "on-primary-fixed": "#2c0051",
        "primary-fixed": "#f0dbff",
        "error": "#ffb4ab"
      },
      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [forms, containerQueries],
};